# ベクトル・行列演算

In [1]:
import numpy as np

## ベクトル

$x = (x_1,...,x_n)$

In [2]:
x = np.arange(5)
print('x = ', x) 
print(x[3])

x =  [0 1 2 3 4]
3


### ベクトルの演算

In [3]:
x = np.array([3.0, 4.0])
y = np.array([2.0, 1.0])

print('x + y = ', x + y) 
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', np.power(x,y))

x + y =  [5. 5.]
x * y =  [6. 4.]
x / y =  [1.5 4. ]
x ** y =  [9. 4.]


## 行列
we can draw a matrix as a table,
where each entry $a_{ij}$ belongs to the $i$-th row and $j$-th column.


$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nm} \\
\end{pmatrix}$$

In [4]:
A = np.arange(12).reshape((3,4))
print('A =', A)
print(A[2,3])

A = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11


### 次元

In [5]:
print(A.ndim)
print(A.shape)
print(A.size)

2
(3, 4)
12


### 転置行列
if $B = A^T$, then $b_{ij} = a_{ji}$ for any $i$ and $j$.

In [6]:
print(A.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 演算

In [7]:
a = 2
x = np.ones((2,3))
y = np.zeros((2,3))-1
print('X =',x)
print('Y =',y)
print('aX =',a*x)
print('aX+Y =',a*x+y)

X = [[1. 1. 1.]
 [1. 1. 1.]]
Y = [[-1. -1. -1.]
 [-1. -1. -1.]]
aX = [[2. 2. 2.]
 [2. 2. 2.]]
aX+Y = [[1. 1. 1.]
 [1. 1. 1.]]


## 総和と平均

In [8]:
print('X=',x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

X= [[1. 1. 1.]
 [1. 1. 1.]]
6.0
[2. 2. 2.]
[3. 3.]


In [9]:
print('A =',A)
print(np.mean(A))
print(np.sum(A) / A.size)
print(np.mean(A,axis=0))
print(np.sum(A,axis=0) / A.shape[0])
print(np.mean(A,axis=1))
print(np.sum(A,axis=1) / A.shape[1])

A = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
5.5
[4. 5. 6. 7.]
[4. 5. 6. 7.]
[1.5 5.5 9.5]
[1.5 5.5 9.5]


## ベクトル内積

Given two vectors $\mathbf{u}$ and $\mathbf{v}$, the dot product $\mathbf{u}^T \mathbf{v}$ is a sum over the products of the corresponding elements: $\mathbf{u}^T \mathbf{v} = \sum_{i=1}^{d} u_i \cdot v_i$.

In [10]:
x = np.arange(4) +1.0
y = np.ones(4)
print('x =',x)
print('y =',y)
print('x・y =',np.dot(x, y))

x = [1. 2. 3. 4.]
y = [1. 1. 1. 1.]
x・y = 10.0


In [ ]:
np.sum(x * y)

10.0

## 行列とベクトルの積

$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nm} \\
\end{pmatrix},\quad\mathbf{x}=\begin{pmatrix}
 x_{1}  \\
 x_{2} \\
\vdots\\
 x_{m}\\
\end{pmatrix} $$

$$A\mathbf{x}=
\begin{pmatrix}
\cdots & \mathbf{a}^T_{1} &...  \\
\cdots & \mathbf{a}^T_{2} & \cdots \\
 & \vdots &  \\
 \cdots &\mathbf{a}^T_n & \cdots \\
\end{pmatrix}
\begin{pmatrix}
 x_{1}  \\
 x_{2} \\
\vdots\\
 x_{m}\\
\end{pmatrix}
= \begin{pmatrix}
 \mathbf{a}^T_{1} \mathbf{x}  \\
 \mathbf{a}^T_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^T_{n} \mathbf{x}\\
\end{pmatrix}
$$

So you can think of multiplication by a matrix $A\in \mathbb{R}^{m \times n}$ as a transformation that projects vectors from $\mathbb{R}^{m}$ to $\mathbb{R}^{n}$.


In [11]:
A = A.reshape((3,4))
print('A =',A)
print('x =',x)
print('A*x =',A * x)
print('Ax =',np.dot(A, x))

A = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
x = [1. 2. 3. 4.]
A*x = [[ 0.  2.  6. 12.]
 [ 4. 10. 18. 28.]
 [ 8. 18. 30. 44.]]
Ax = [ 20.  60. 100.]


## 行列積

If you've gotten the hang of dot products and matrix-vector multiplication, then matrix-matrix multiplications should be pretty straightforward.

Say we have two matrices, $A \in \mathbb{R}^{n \times k}$ and $B \in \mathbb{R}^{k \times m}$:

$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1k} \\
 a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{pmatrix},\quad
B=\begin{pmatrix}
 b_{11} & b_{12} & \cdots & b_{1m} \\
 b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{pmatrix}$$

$$AB = \begin{pmatrix}
\cdots & \mathbf{a}^T_{1} &...  \\
\cdots & \mathbf{a}^T_{2} & \cdots \\
 & \vdots &  \\
 \cdots &\mathbf{a}^T_n & \cdots \\
\end{pmatrix}
\begin{pmatrix}
\vdots & \vdots &  & \vdots \\
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
 \vdots & \vdots &  &\vdots\\
\end{pmatrix}
= \begin{pmatrix}
\mathbf{a}^T_{1} \mathbf{b}_1 & \mathbf{a}^T_{1}\mathbf{b}_2& \cdots & \mathbf{a}^T_{1} \mathbf{b}_m \\
 \mathbf{a}^T_{2}\mathbf{b}_1 & \mathbf{a}^T_{2} \mathbf{b}_2 & \cdots & \mathbf{a}^T_{2} \mathbf{b}_m \\
 \vdots & \vdots & \ddots &\vdots\\
\mathbf{a}^T_{n} \mathbf{b}_1 & \mathbf{a}^T_{n}\mathbf{b}_2& \cdots& \mathbf{a}^T_{n} \mathbf{b}_m
\end{pmatrix}
$$

You can think of the matrix-matrix multiplication $AB$ as simply performing $m$ matrix-vector products and stitching the results together.

In [12]:
B = np.ones(shape=(4, 3))
print('A =',A)
print('B =',B)
print('AB =',np.dot(A, B))

A = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
AB = [[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]]


numpy.dot(a, b, out=None)
Dot product of two arrays. Specifically,

- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

- If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

- If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

- If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

## ノルム

All norms must satisfy a handful of properties:

1. $\|\alpha A\| = |\alpha| \|A\|$
1. $\|A + B\| \leq \|A\| + \|B\|$
1. $\|A\| \geq 0$
1. If $\forall {i,j}, a_{ij} = 0$, then $\|A\|=0$

In [13]:
print('||x|| =',np.linalg.norm(x))
print('||A|| =',np.linalg.norm(A))

||x|| = 5.477225575051661
||A|| = 22.494443758403985
